apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      type: front-end
  template:
    metadata:
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
      - name: myapp-container
        image: busybox
        kubectl apply -f /Users/smathew/Documents/harvard/training/Github Copilot/copilot-dd/deployment.yaml
